"""001_initial_schema

Revision ID: 5b7d1904cef7
Revises: 
Create Date: 2026-10-01 23:31:22.993390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7d1904cef7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('lab_name', sa.String(length=80), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('working_status', sa.Enum('FUNCTIONAL', 'NEEDS_REPAIR', 'NON_FUNCTIONAL', name='equipment_working_status_enum', native_enum=False), nullable=False),
    sa.Column('maintenance_status', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_equipment_equipment_id'), 'lab_equipment', ['equipment_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'WARDEN', 'HOSTEL_FACULTY', 'TEACHER', 'LAB_ASSISTANT', 'STAFF', 'GUARD', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('theme_preference', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_session_date'), 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('class_notices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('notice_type', sa.Enum('CANCELLED', 'POSTPONED', 'RESCHEDULED', 'SWITCHED', 'ROOM_CHANGED', 'FACULTY_CHANGED', name='class_notice_type_enum', native_enum=False), nullable=False),
    sa.Column('target_branch', sa.String(length=50), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('target_semester', sa.Integer(), nullable=False),
    sa.Column('target_section', sa.String(length=5), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('class_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_notices_teacher_id'), 'class_notices', ['teacher_id'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('warden_id', sa.Uuid(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warden_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_code'), 'hostels', ['code'], unique=True)
    op.create_index(op.f('ix_hostels_warden_id'), 'hostels', ['warden_id'], unique=False)
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_created_at'), 'in_app_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_entity_id'), 'in_app_notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_type'), 'in_app_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_user_id'), 'in_app_notifications', ['user_id'], unique=False)
    op.create_table('lab_requisitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requisition_number', sa.String(length=30), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('lab_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ORDERED', 'COMPLETED', name='lab_requisition_status_enum', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_requisitions_assistant_id'), 'lab_requisitions', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_lab_requisitions_created_at'), 'lab_requisitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_requisitions_requisition_number'), 'lab_requisitions', ['requisition_number'], unique=True)
    op.create_index(op.f('ix_lab_requisitions_status'), 'lab_requisitions', ['status'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('assigned_lab_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_materials_teacher_id'), 'study_materials', ['teacher_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT', name='announcement_priority_enum', native_enum=False), nullable=False),
    sa.Column('target_branch', sa.String(length=50), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('target_section', sa.String(length=5), nullable=True),
    sa.Column('target_hostel_id', sa.Uuid(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_priority'), 'announcements', ['priority'], unique=False)
    op.create_index(op.f('ix_announcements_target_hostel_id'), 'announcements', ['target_hostel_id'], unique=False)
    op.create_table('lab_requisition_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requisition_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('specifications', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('justification', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['lab_requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_requisition_items_requisition_id'), 'lab_requisition_items', ['requisition_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('dues_cleared', sa.Boolean(), nullable=False),
    sa.Column('has_smartphone', sa.Boolean(), nullable=False),
    sa.Column('parent_phone', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_hostel_id'), 'students', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_table('study_material_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_material_targets_material_id'), 'study_material_targets', ['material_id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'student_id', name='uq_announcement_student_read')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_student_id'), 'announcement_reads', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendance_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student_attendance')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.String(length=40), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('location_details', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED', 'COMPLETED', name='complaint_status_enum', native_enum=False), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_complaint_rating'),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assigned_staff_id'), 'complaints', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_complaints_category_id'), 'complaints', ['category_id'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_is_recurring'), 'complaints', ['is_recurring'], unique=False)
    op.create_index(op.f('ix_complaints_sla_deadline'), 'complaints', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_student_id'), 'complaints', ['student_id'], unique=False)
    op.create_index(op.f('ix_complaints_ticket_number'), 'complaints', ['ticket_number'], unique=True)
    op.create_table('document_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_number', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('BONAFIDE', 'HOSTEL_RESIDENCE', 'FEE_ESTIMATE', name='document_type_enum', native_enum=False), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='document_request_status_enum', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('verification_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_request_number'), 'document_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_index(op.f('ix_document_requests_student_id'), 'document_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_document_requests_verification_hash'), 'document_requests', ['verification_hash'], unique=True)
    op.create_table('gate_passes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pass_number', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('pass_type', sa.Enum('DAY_OUTING', 'HOME_LEAVE', name='gate_pass_type_enum', native_enum=False), nullable=False),
    sa.Column('out_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHECKED_OUT', 'COMPLETED', 'OVERDUE', name='gate_pass_status_enum', native_enum=False), nullable=False),
    sa.Column('decision_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='decision_status_enum', native_enum=False), nullable=False),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('actual_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pin_code', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_passes_actual_in_time'), 'gate_passes', ['actual_in_time'], unique=False)
    op.create_index(op.f('ix_gate_passes_actual_out_time'), 'gate_passes', ['actual_out_time'], unique=False)
    op.create_index(op.f('ix_gate_passes_created_at'), 'gate_passes', ['created_at'], unique=False)
    op.create_index(op.f('ix_gate_passes_decision_at'), 'gate_passes', ['decision_at'], unique=False)
    op.create_index(op.f('ix_gate_passes_decision_status'), 'gate_passes', ['decision_status'], unique=False)
    op.create_index(op.f('ix_gate_passes_pass_number'), 'gate_passes', ['pass_number'], unique=True)
    op.create_index(op.f('ix_gate_passes_status'), 'gate_passes', ['status'], unique=False)
    op.create_index(op.f('ix_gate_passes_student_id'), 'gate_passes', ['student_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_student_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_beneficiary_student_id'), 'otp_verifications', ['beneficiary_student_id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_expires_at'), 'otp_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_verifications_is_verified'), 'otp_verifications', ['is_verified'], unique=False)
    op.create_table('sms_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=15), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_notifications_student_id'), 'sms_notifications', ['student_id'], unique=False)
    op.create_table('complaint_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_attachments_complaint_id'), 'complaint_attachments', ['complaint_id'], unique=False)
    op.create_table('gate_pass_qr_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gate_pass_id', sa.Uuid(), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_guard_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='qr_token_status_enum', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['gate_pass_id'], ['gate_passes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_guard_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_pass_id')
    )
    op.create_index(op.f('ix_gate_pass_qr_tokens_expires_at'), 'gate_pass_qr_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_gate_pass_qr_tokens_qr_token'), 'gate_pass_qr_tokens', ['qr_token'], unique=True)
    op.create_index(op.f('ix_gate_pass_qr_tokens_status'), 'gate_pass_qr_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_gate_pass_qr_tokens_student_id'), 'gate_pass_qr_tokens', ['student_id'], unique=False)
    op.create_index(op.f('ix_gate_pass_qr_tokens_used_at'), 'gate_pass_qr_tokens', ['used_at'], unique=False)
    op.create_table('proxy_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('proxy_student_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_student_id', sa.Uuid(), nullable=False),
    sa.Column('otp_verification_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['otp_verification_id'], ['otp_verifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otp_verification_id')
    )
    op.create_index(op.f('ix_proxy_requests_beneficiary_student_id'), 'proxy_requests', ['beneficiary_student_id'], unique=False)
    op.create_index(op.f('ix_proxy_requests_entity_id'), 'proxy_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_proxy_requests_proxy_student_id'), 'proxy_requests', ['proxy_student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_requests_proxy_student_id'), table_name='proxy_requests')
    op.drop_index(op.f('ix_proxy_requests_entity_id'), table_name='proxy_requests')
    op.drop_index(op.f('ix_proxy_requests_beneficiary_student_id'), table_name='proxy_requests')
    op.drop_table('proxy_requests')
    op.drop_index(op.f('ix_gate_pass_qr_tokens_used_at'), table_name='gate_pass_qr_tokens')
    op.drop_index(op.f('ix_gate_pass_qr_tokens_student_id'), table_name='gate_pass_qr_tokens')
    op.drop_index(op.f('ix_gate_pass_qr_tokens_status'), table_name='gate_pass_qr_tokens')
    op.drop_index(op.f('ix_gate_pass_qr_tokens_qr_token'), table_name='gate_pass_qr_tokens')
    op.drop_index(op.f('ix_gate_pass_qr_tokens_expires_at'), table_name='gate_pass_qr_tokens')
    op.drop_table('gate_pass_qr_tokens')
    op.drop_index(op.f('ix_complaint_attachments_complaint_id'), table_name='complaint_attachments')
    op.drop_table('complaint_attachments')
    op.drop_index(op.f('ix_sms_notifications_student_id'), table_name='sms_notifications')
    op.drop_table('sms_notifications')
    op.drop_index(op.f('ix_otp_verifications_is_verified'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_expires_at'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_beneficiary_student_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_gate_passes_student_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_status'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_pass_number'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_decision_status'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_decision_at'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_created_at'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_actual_out_time'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_actual_in_time'), table_name='gate_passes')
    op.drop_table('gate_passes')
    op.drop_index(op.f('ix_document_requests_verification_hash'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_student_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_request_number'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_complaints_ticket_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_student_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_sla_deadline'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_is_recurring'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_staff_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_announcement_reads_student_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_study_material_targets_material_id'), table_name='study_material_targets')
    op.drop_table('study_material_targets')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_hostel_id'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_lab_requisition_items_requisition_id'), table_name='lab_requisition_items')
    op.drop_table('lab_requisition_items')
    op.drop_index(op.f('ix_announcements_target_hostel_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_priority'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_study_materials_teacher_id'), table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_table('staff')
    op.drop_index(op.f('ix_lab_requisitions_status'), table_name='lab_requisitions')
    op.drop_index(op.f('ix_lab_requisitions_requisition_number'), table_name='lab_requisitions')
    op.drop_index(op.f('ix_lab_requisitions_created_at'), table_name='lab_requisitions')
    op.drop_index(op.f('ix_lab_requisitions_assistant_id'), table_name='lab_requisitions')
    op.drop_table('lab_requisitions')
    op.drop_index(op.f('ix_in_app_notifications_user_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_type'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_is_read'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_entity_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_created_at'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    op.drop_index(op.f('ix_hostels_warden_id'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_code'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_class_notices_teacher_id'), table_name='class_notices')
    op.drop_table('class_notices')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_date'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lab_equipment_equipment_id'), table_name='lab_equipment')
    op.drop_table('lab_equipment')
    # ### end Alembic commands ###
